### ISSUE TITLE
easy-format interface error

### ISSUE THREAD

**Issue by mars0i** [alavrik/piqi-ocaml#11]
Hi,

Thanks very much for developing `piqi`.  After cloning the repo, I'm having some trouble compiling `piqi-ocaml` with OCaml `4.06.0+flambda`.  (I'm assuming that flambda isn't the problem.)  I've already compiled and installed `piqi` from the repo without trouble.  (The version of `piqi` in opam 
wants pre-4.0.2 versions of OCaml.)

(I should note that I had to install `ulex`, `base64`, and `easy-format`; these weren't mentioned in the installation instructions in README.md.)

I get the following error with `easy-format` 1.3.1 (current), 1.3.0, 1.2.0, and 1.1.0, and 1.0.2.  Version 1.0.1 wouldn't build.  (These are all of the versions that `opam list` currently reports.)
```
ocamlfind ocamlopt \
				-package piqilib,bytes -linkpkg \
				    -I ../piqirun        ../piqirun/piqirun.cmxa    -o piqic-ocaml \
				piqic_piqi.cmx piqic_common.cmx piqic_ocaml_types.cmx piqic_ocaml_out.cmx piqic_ocaml_in.cmx piqic_ocaml_defaults.cmx piqic_ocaml_ext.cmx piqic_ocaml_version.cmx piqic_ocaml.cmx
File "_none_", line 1:
Error: Files /Users/marshall/.opam/4.06.0+flambda/lib/piqilib/piqilib.cmxa
       and /Users/marshall/.opam/4.06.0+flambda/lib/easy-format/easy_format.cmxa
       make inconsistent assumptions over interface Easy_format
make[2]: *** [piqic-ocaml] Error 2
make[1]: *** [native-code] Error 2
make: *** [dirs] Error 2
```

**Comment by mars0i** [comment]
I don't get the error on my other machine.  Both are MacOS 10.11.6 but one is older, and I think there are difference in libraries.  I'm surprised that this would generate the error listed above, but I'll see if I can figure out might be different.  I still haven't figured out, however, where the relevant source file for `piqilib.cmxa` is.  Working on that.

**Comment by alavrik** [comment]
@mars0i Only the master branches support OCaml 4.06 (tracked in https://github.com/alavrik/piqi/issues/57)

Can you try installing both piqi and piqi-ocaml from master branches and see if it works? You can find instructions for installing development versions here: https://github.com/alavrik/piqi-ocaml/blob/master/README.md#installing-using-opam
