### ISSUE TITLE
Piqirun.init_from_channel and parse on socket channel ?

### ISSUE THREAD

**Issue by RobinDavid** [alavrik/piqi-ocaml#6]
I am struggling trying to parse data coming from in input channel made out of a socket. The problem is that the parse_XXXX call hangs forever. Here is a small sample:

```ocaml
(*  [...] *)
let (s, caller) = Unix.accept sock in
let ic = Unix.in_channel_of_descr s in
let buf = Piqirun.init_from_channel ic in
parse_xxxx buf (* hangs forever *)
```

The parse function hangs forever until the socket is closed on the other side. I am supposing that parsing using a buffer does parse until an End_of_file or End_of_buffer exception is raised (which is maybe never the case for a socket channel). Could it be something like that ? Do you have any idea ?

*Note: it works pretty fine on files*

I am so desperate trying to solve this problem that any clue would be helpful.

Regards,

**Comment by alavrik** [comment]
It looks like you are using it incorrectly. Protocol buffer messages don't have a frame. So, whenever you are writing a message to a stream, unless you enclose the message into some kind of a frame, it is going to extend until the end of the stream.

You'll need to figure what kind of framing format the sender uses. After that, you'll need to do something like that:

**Comment by RobinDavid** [comment]
Ok, thanks a lot, I naively though it was made automatically by the parser function itself.

I will consider doing it that way :wink:
