### ISSUE TITLE
Please allow fully qualified module names to facilitate proper reuse

### ISSUE THREAD

**Issue by KennethAdamMiller** [alavrik/piqi-ocaml#7]
In the even that you should have a widely used library that has it's own schema, and you want to reuse that schema, you will run into compiler errors.

There's two ways to reuse a schema that someone else defines-import or include it. 

Including it you can easily see you will get compile errors because in languages like ocaml, you will, at some points be producing types that are of one instance of the piqi generated module instance (1, that is not included, original to your hypothetical library), and then trying to mix or do operations on or otherwise use properly instances of the *other* piqi generated module instance (2, that *is* included, that you are duplicating from the hypothetical library). 

Importing a module from a provided library is the proper way, but this introduces errors if there is a module path that you have to qualify the original library's generated module types to in order for the compiler to see that the types are indeed equivalent. Lo, if you try and just use a module that is defined nested within another rawly, you'll get an error.

Ergo my post :)

.import [
  .module library_piqi_defs .name fully.qualified.module.path.library_piqi_defs
]

**Comment by alavrik** [comment]
Importing is definitely the way to go. Includes are more subtle and rarely needed in application code.

Just pushed a small [addition](https://github.com/alavrik/piqi-ocaml/commit/eb446e454757d523ea5750c2adbcfb803bb4a7d1). Let me know if it helps.

For example, given an import statement like this:
```
.import [
    .module m
    .ocaml-module "Foo.Bar"
    .ocaml-name "Fum"
]
```
piqic-ocaml will generate the following statement at the top of the generated
_piqi.ml:
```ocaml
module Fum = Foo.Bar
```

**Comment by KennethAdamMiller** [comment]
Thank you tremendously! Would tip you for that if I could. Fast and
accurate update! I'll try it out asap.

**Comment by KennethAdamMiller** [comment]
Actually, is it possible to somehow specify in piqi that a type within an
imported module is equivalent to another type?

**Comment by KennethAdamMiller** [comment]
Nevermind, I found that through just renaming the submodule that it was
specific to and exposing that type there, that I could get what I needed.
